### ISSUE TITLE
Start Creating Text Collection with the USFM Data Provider

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-extension-text-collection#1]
Create a view for text collection similar to the text collection in Paratext.

This can use mock data to simulate other projects/resources, but it does not need to use mock data and can reuse the same data from the USFM data provider

**Comment by FoolRunning** [comment]
Here is the created repository for this: https://github.com/paranext/paranext-extension-text-collection

**Comment by rolfheij-sil** [comment]
Initial version is done. 

Some additional work is needed:
- The 'Open Text Collection' button from the main menu should be hooked up to some dialog that allows you to configure the text collection. This is a separate task.
- Said dialog should be created. This is a separate task.
- A global verse reference / BCV control should be created. This is a separate task.
- The text collection should get data from actual resources, instead of getting mock data from the USFM provider. This is a separate task.

Non-separate tasks:
- The global verse reference / BCV control that is to be created should be hooked up to the text collection
- The text in the title bar of the text collection should be updated dynamically. Right now I don't believe that this is possible.
- Allow the splitter that appears when a full chapter is shown to be draggable
- Add a context menu to the project entries, like it appears in Paratext 9

Small things:
- Make sure close button doesn't overlap with the text of the full chapter
- Show book name instead of book number in title bar

**Comment by tjcouch-sil** [comment]
We found a small problem (maybe related to the window being thin?):

![Image](https://github.com/paranext/paranext-extension-text-collection/assets/104016682/7d063996-5f50-4f18-b97b-127f5a660bf5)
